server:
  port: 8080
spring:
  cloud:
    gateway:
      routes:
        - id: employee-service
          uri: lb://EMPLOYEE-SERVICE
          predicates:
            - Path=/employees/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
