server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: department-service
          uri: lb://department-service
          predicates:
            - Path=/departments/**
        - id: employee-service
          uri: lb://employee-service
          predicates:
            - Path=/employees/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
